[bot]
name = "Taiga"
status = "online"
activity = "The cutest cat on Discord"
prefix = "t."

[github]
owner = "JadenLabs"
name = "Taiga"
commits_per_page = 9

[ids]
sudo_users = [
    1027380375028244551, # roc.py - lead dev
]
home_guild = 0 # 1190449108415152199 - taiga supremacy

[colors]
primary = 0xE7C7EF
secondary = 0xF7DB69
invisible = 0x2B2D31
success = 0x00D355
error = 0xDF0043

[emojis]
# Core emojis
arrow_right = "<:arrow_right:1268049170267373589>"
chat = "<:chat:1268049281051525164>"
dns = "<:dns:1268049301620265011>"
true = "<:true:1268049349145788540>"
false = "<:false:1268049317520740394>"
ping = "<:ping:1268049331064143924>"
# Taiga emojis
beans = "ğŸ«˜"
fish = "ğŸŸ"
heart = ":purple_heart:"
loading = "<a:loading:1193049795082858597>"
BLF = "<:BLF:1268049263187722311>"
BLE = "<:BLE:1268049249392656484>"
BMF = "<:BMF:1268049231483109438>"
BME = "<:BME:1268049217352499200>"
BRF = "<:BRF:1268049203184013323>"
BRE = "<:BRE:1268049187958952029>"

[beans]
[beans.pets]
min = 200
max = 500

[cooldowns]
pet = 43200

[leaderboards]
default_page_size = 10

[messages]
fishing = [
    "How much grass have you touched this week?",
    "You're petting Taiga daily, right??",
    "Hail Taiga.",
]
